In [1]:
import numpy as np
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
#import matplotlib.pyplot as plt

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# Hypothesis using mattix

#          (w1
#(x1,x2,x3) w2  = (x1w1 + x2w2 + x3w3)
#           w3)

# matrix형태 계산시 한번?에 계산 가능(여러 인스턴스를 하나의 mastrix에 넣어 계산)
#[5,3]*[3,1]=[5,1]

# n output
# [n, 3]*[3,2]=[n,2]

In [3]:
tf.set_random_seed(777)

# 개별 인스턴스 학습

In [4]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]


In [6]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [16]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 20 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  77437.83 
Prediction:
 [ -99.19784 -109.40472 -112.99919 -123.97137  -79.7757 ]
20 Cost:  9.441353 
Prediction:
 [147.72311 187.33174 179.40321 194.44539 146.55028]
40 Cost:  9.343039 
Prediction:
 [147.74861 187.31851 179.41298 194.45387 146.53104]
60 Cost:  9.245787 
Prediction:
 [147.7717  187.30264 179.41998 194.45941 146.50981]
80 Cost:  9.149615 
Prediction:
 [147.79465 187.28685 179.42696 194.4649  146.48871]
100 Cost:  9.054449 
Prediction:
 [147.81749 187.27113 179.43388 194.47038 146.46773]
120 Cost:  8.960345 
Prediction:
 [147.8402  187.25552 179.4408  194.47581 146.44685]
140 Cost:  8.867208 
Prediction:
 [147.86278 187.23999 179.44763 194.48123 146.42607]
160 Cost:  8.775106 
Prediction:
 [147.88525 187.22456 179.4545  194.48665 146.40544]
180 Cost:  8.683998 
Prediction:
 [147.90758 187.20918 179.46126 194.49199 146.38489]
200 Cost:  8.593813 
Prediction:
 [147.92982 187.19392 179.46803 194.49734 146.36446]
220 Cost:  8.504641 
Prediction:
 [147.9519  187.17871 

# Matrix 형택 학습

In [4]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3]) # None = n개, 3 = 3열
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight') # Weight의 모양 = [3, 1]
b = tf.Variable(tf.random_normal([1]), name='bias') # bias의 모양 = [1]

In [5]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [8]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(1001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  2861.9668 
Prediction:
 [[105.63413 ]
 [126.47547 ]
 [125.023895]
 [135.61624 ]
 [ 96.54288 ]]
100 Cost:  1.789065 
Prediction:
 [[153.03859]
 [183.54329]
 [181.20644]
 [196.80182]
 [140.09048]]
200 Cost:  1.708155 
Prediction:
 [[152.99164]
 [183.57559]
 [181.1922 ]
 [196.79037]
 [140.13387]]
300 Cost:  1.6314819 
Prediction:
 [[152.94594]
 [183.60704]
 [181.17836]
 [196.77919]
 [140.1761 ]]
400 Cost:  1.558845 
Prediction:
 [[152.9015 ]
 [183.63765]
 [181.16487]
 [196.76831]
 [140.21722]]
500 Cost:  1.4900503 
Prediction:
 [[152.85823]
 [183.66739]
 [181.15176]
 [196.75769]
 [140.25725]]
600 Cost:  1.4248439 
Prediction:
 [[152.81616]
 [183.69637]
 [181.139  ]
 [196.74731]
 [140.29623]]
700 Cost:  1.3630717 
Prediction:
 [[152.7752 ]
 [183.72455]
 [181.12659]
 [196.73718]
 [140.33417]]
800 Cost:  1.3045632 
Prediction:
 [[152.73538]
 [183.75198]
 [181.11456]
 [196.72736]
 [140.37114]]
900 Cost:  1.2491057 
Prediction:
 [[152.69662]
 [183.77867]
 [181.10281]
 [196.71773]
 [14

# Matrix 형택 학습 - Load Xmatrix

In [9]:
path = 'D:/WorkSpace/Python/강의자료 구현/DeepLearningZeroToAll-master/'
xy = np.loadtxt(path+'data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [10]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(1001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)


0 Cost: 68479.24 
Prediction:
 [[ -96.46343 ]
 [-109.81928 ]
 [-111.79769 ]
 [-119.038536]
 [ -84.00308 ]
 [ -56.08633 ]
 [ -86.056404]
 [ -59.935307]
 [ -97.40455 ]
 [ -83.02706 ]
 [ -83.865944]
 [ -78.64712 ]
 [-118.44631 ]
 [-101.81907 ]
 [ -85.158585]
 [-109.30164 ]
 [ -98.36591 ]
 [-103.39904 ]
 [-114.2934  ]
 [-102.214226]
 [-101.391   ]
 [-100.46287 ]
 [ -97.95316 ]
 [-103.9799  ]
 [-116.30046 ]]
100 Cost: 17.887838 
Prediction:
 [[149.70439]
 [185.80379]
 [179.61821]
 [198.2637 ]
 [141.45518]
 [109.99501]
 [151.41817]
 [116.06918]
 [178.73096]
 [172.56065]
 [144.92833]
 [146.81187]
 [182.69577]
 [148.60406]
 [153.36256]
 [190.64073]
 [140.13942]
 [181.60585]
 [172.85208]
 [154.72633]
 [177.07562]
 [176.81699]
 [167.58429]
 [144.37811]
 [190.15141]]
200 Cost: 16.924921 
Prediction:
 [[149.85117 ]
 [185.74252 ]
 [179.68599 ]
 [198.26912 ]
 [141.40578 ]
 [109.82514 ]
 [151.38712 ]
 [116.004135]
 [178.53496 ]
 [172.20662 ]
 [144.8978  ]
 [146.65063 ]
 [182.83162 ]
 [148.79875 ]
 [1

# Queue Runners

### - Queue Runners 참고 : https://blog.naver.com/heartflow89/221086772536

In [5]:
path = 'D:/WorkSpace/Python/강의자료 구현/DeepLearningZeroToAll-master/'

In [8]:
# Lab 4 Multi-variable linear regression
# https://www.tensorflow.org/programmers_guide/reading_data

# tf.train.string_input_producer
# filename 목록을 넘겨받음 
# ex : tf.train.string_input_producer(["file0.csv", "file1.csv", ......])
# name: A name for the operation (optional).
filename_queue = tf.train.string_input_producer(
    [path + 'data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader() # 파일의 한줄씩 읽어서 리턴
key, value = reader.read(filename_queue)
# value : 파일에서 읽은 값
# key : (파일 이름인듯)b'D:/WorkSpace/Python/\xea\xb0\x95\xec\x9d\x98\xec\x9e\x90\xeb\xa3\x8c \xea\xb5\xac\xed\x98\x84/DeepLearningZeroToAll-master/data-01-test-score.csv:1'

In [9]:
# Check Point

#sess = tf.Session()
#sess.run(tf.global_variables_initializer())
#coord = tf.train.Coordinator()
#threads = tf.train.start_queue_runners(sess=sess, coord=coord)
#sess.run(key)
#sess.run(value)

In [10]:
# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]] # 입력 변수의 type 및 null값 처리
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10) # batch_size : 10등분

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).


In [11]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(1001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

0 Cost:  2598.893 
Prediction:
 [[105.63413 ]
 [126.47547 ]
 [125.023895]
 [135.61624 ]
 [ 96.54288 ]
 [ 69.79834 ]
 [100.468285]
 [ 73.146675]
 [117.17079 ]
 [106.953476]]
100 Cost:  11.245397 
Prediction:
 [[154.6236 ]
 [185.49474]
 [183.09875]
 [198.94257]
 [141.5244 ]
 [103.09856]
 [147.94803]
 [108.44992]
 [172.45642]
 [158.34714]]
200 Cost:  10.604915 
Prediction:
 [[154.53923]
 [185.51482]
 [183.04994]
 [198.96269]
 [141.50941]
 [103.21482]
 [148.03806]
 [108.61786]
 [172.59294]
 [158.64653]]
300 Cost:  10.022897 
Prediction:
 [[154.45927]
 [185.53311]
 [183.00323]
 [198.98215]
 [141.49379]
 [103.32515]
 [148.12506]
 [108.78026]
 [172.72246]
 [158.9321 ]]
400 Cost:  9.493998 
Prediction:
 [[154.38356 ]
 [185.54974 ]
 [182.95862 ]
 [199.00096 ]
 [141.47762 ]
 [103.429794]
 [148.20918 ]
 [108.93735 ]
 [172.84534 ]
 [159.20451 ]]
500 Cost:  9.013475 
Prediction:
 [[154.31184]
 [185.5648 ]
 [182.916  ]
 [199.01913]
 [141.46095]
 [103.52904]
 [148.29048]
 [109.08928]
 [172.96185]
 [1

In [12]:
# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[184.1228]]
Other scores will be  [[162.44106]
 [182.35104]]
