In [3]:
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

import numpy as np
import pprint # 예쁜 출력
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

C:\Users\kih\Anaconda3\envs\tf_py36\lib\site-packages\tensorflow\python\client\session.py:1761: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


# 1차원 Arraym

In [7]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank(?), 1차원 array
print(t.shape) # shape
print(t[0], t[1], t[-1], t[2:5], t[4:-1], t[:2], t[3:]) # slince

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0 [2. 3. 4.] [4. 5.] [0. 1.] [3. 4. 5. 6.]


# 2차원 Array

In [9]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


# Shape, Rank, Axis

In [13]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval() # [1. ,2. ,3. ,4. ](1차원 array)

array([4])

In [14]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval() # 2차원

array([2, 2])

In [15]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval() # 4차원, [axis 0, axis 1, axis 2, axis 3]

array([1, 2, 3, 4])

In [16]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

# Matmul VS multiply

In [19]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print(matrix1.shape)
print(matrix2.shape)
tf.matmul(matrix1, matrix2).eval()
# (matrix1*matrix2).eval() # 그냥 곱하면 안됨, matrix 계산 아님
# (3, 3) * (2  = [12]
#           2)

(1, 2)
(2, 1)


array([[12.]], dtype=float32)

# Watch out broadcasting

In [24]:
# broadcating : 다른 차원에 대해서도 계산 가능
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print((matrix1+matrix2).eval())

print("="*100)
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
print((matrix1+matrix2).eval())

[[5. 5.]
 [5. 5.]]
[[5. 5.]]


# Reduce Mean/Sum

In [28]:
# int값 입력시 계산도 int로 계산됨, float type으로 입력해야함.
print(tf.reduce_mean([1, 2], axis=0).eval())
print(tf.reduce_mean([1. , 2. ], axis=0).eval())

1
1.5


In [27]:
x = [[1., 2.],
     [3., 4.]]
tf.reduce_mean(x).eval()

2.5

In [43]:
# mean
print(tf.reduce_mean(x, axis=0).eval()) # 열단위
print(tf.reduce_mean(x, axis=1).eval()) # 행단위
print(tf.reduce_mean(x, axis=-1).eval()) # 행단위
# sum
print(tf.reduce_sum(x).eval())
print(tf.reduce_sum(x, axis=0).eval())
print(tf.reduce_sum(x, axis=-1).eval())

[2. 3.]
[1.5 3.5]
[1.5 3.5]
10.0
[4. 6.]
[3. 7.]


# Argmax with axi

In [47]:
x = [[0, 1, 2],
     [2, 1, 0],
     [3, 0, 0]]
tf.argmax(x, axis=0).eval() # 값이 아닌 위치(max 값) 출력

array([2, 0, 0], dtype=int64)

# Reshape(squeeze, expand_dims)

In [51]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [52]:
tf.reshape(t, shape=[-1, 3]).eval() # -1 : 알아서???

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [54]:
# squeeze : 차원 중 사이즈 1인 것을 찾아서 제거
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

In [62]:
# expand_dims(x, n) : n번째 차원을 추가하여 확장
print(tf.expand_dims([0, 1, 2], 0).eval())
print(tf.expand_dims([0, 1, 2], 0).eval().shape)
print()
print(tf.expand_dims([0, 1, 2], 1).eval())
print(tf.expand_dims([0, 1, 2], 1).eval().shape)

[[0 1 2]]
(1, 3)

[[0]
 [1]
 [2]]
(3, 1)


# One hot

In [63]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [64]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

# Casting

In [65]:
# int 변환
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [67]:
# boolean -> int
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

# Stack

In [68]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

# Ones like and Zeros like

In [75]:
x = [[0, 1, 2],
     [2, 1, 0]]

# 동일 shape의 0 또는 1의 array
print(tf.ones_like(x).eval())
print()
print(tf.zeros_like(x).eval())

[[1 1 1]
 [1 1 1]]

[[0 0 0]
 [0 0 0]]


# Zip

In [ ]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

In [ ]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

# Random values for variable initializations

In [76]:
print(tf.random_normal([3]).eval())
print(tf.random_uniform([2]).eval())
print(tf.random_uniform([2, 3]).eval())

[0.58597755 0.55676264 0.25931567]
[0.4934088 0.7006384]
[[0.43208718 0.59306157 0.289109  ]
 [0.05489087 0.07509768 0.6214081 ]]


# Transpose

In [77]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [78]:
# [0, 1, 2] : 원래 축 그대로
# (2, 2, 3) -> (2, 2, 3)
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [80]:
# [0, 1, 2] -> [1, 2, 0]
# (2, 2, 3) -> (2, 3, 2)
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])
